version: '3.7'

services:
    app:
        container_name: frontendservice
        image: frontendservice
        build: ./
        ports:
            - "8080:8080"
        networks:
            - docker-network
networks:
    docker-network:
        driver: bridge